# Generated by Django 6.0.6 on 2026-07-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('icon', models.CharField(default='fa-building', help_text='FontAwesome icon class name (e.g., fa-mosque, fa-hotel)', max_length=50)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=20)),
                ('subjek', models.CharField(max_length=150)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramUnggulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class name (e.g., fa-book-quran, fa-laptop-code)', max_length=50)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Program Unggulan',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., Wali Santri, Alumni, Tokoh Masyarakat', max_length=100)),
                ('pesan', models.TextField()),
                ('foto_url', models.URLField(blank=True, help_text='Optional avatar image URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimoni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendaftaranSantri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('nama_orang_tua', models.CharField(max_length=150)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Review'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_pilihan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pesantren.programunggulan')),
            ],
            options={
                'verbose_name_plural': 'Pendaftaran Santri',
                'ordering': ['-created_at'],
            },
        ),
    ]
