# Generated by Django 6.0.6 on 2026-07-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pesantren", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendaftaransantri",
            name="program_pilihan",
            field=models.CharField(
                choices=[
                    ("MTS", "Madrasah Tsanawiyah (MTs)"),
                    ("MA", "Madrasah Aliyah (MA)"),
                ],
                default="MTS",
                max_length=3,
                verbose_name="Jenjang",
            ),
        ),
    ]
