# Generated by Django 6.0.6 on 2026-07-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pesantren", "0002_alter_pendaftaransantri_program_pilihan"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesankontak",
            name="source",
            field=models.CharField(
                choices=[("form", "Form Web"), ("wa", "WhatsApp")],
                default="form",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pesankontak",
            name="wa_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="WA ID / JID",
            ),
        ),
        migrations.AlterField(
            model_name="pesankontak",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="pesankontak",
            name="nama",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pesankontak",
            name="subjek",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
